default:
  target: dev
  outputs:
    dev:
      type: snowflake
      threads: 16
      account: HTFMOKR-ITA25167
      user: LATHIBAD
      database: analytics
      warehouse: transforming
      schema: dbt_lthibadoux
      password: X9#tZ!R@Lm2$Qp
      role: ACCOUNTADMIN

